// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1nRn_r0E_8WAWQfQOr9l4-eqhNlpEOtc',
    appId: '1:69267357220:web:441c10ba40164d2094a2b1',
    messagingSenderId: '69267357220',
    projectId: 'fluttertest-946a6',
    authDomain: 'fluttertest-946a6.firebaseapp.com',
    storageBucket: 'fluttertest-946a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBluVK36WZzHgDLtP9ZJmg3XAUpS3sKq9s',
    appId: '1:69267357220:android:adb783f525bcf0f994a2b1',
    messagingSenderId: '69267357220',
    projectId: 'fluttertest-946a6',
    storageBucket: 'fluttertest-946a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6WRt3JSPt6ujav_ddXDrZtJ0optbXS8s',
    appId: '1:69267357220:ios:fb6ded54f167648194a2b1',
    messagingSenderId: '69267357220',
    projectId: 'fluttertest-946a6',
    storageBucket: 'fluttertest-946a6.appspot.com',
    iosClientId: '69267357220-i8i57aka4bdq9redq69islt0d843rt3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6WRt3JSPt6ujav_ddXDrZtJ0optbXS8s',
    appId: '1:69267357220:ios:fb6ded54f167648194a2b1',
    messagingSenderId: '69267357220',
    projectId: 'fluttertest-946a6',
    storageBucket: 'fluttertest-946a6.appspot.com',
    iosClientId: '69267357220-i8i57aka4bdq9redq69islt0d843rt3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );
}
